name: chat
description: "A new Flutter package project."
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1

  ui_kit:
    path: ../../core/ui_kit

  api_client:
    path: ../../core/api_client
    

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  json_serializable: ^6.9.4


flutter:
  uses-material-design: true

